# Generated by Django 3.2.5 on 2021-08-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_modelpractice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelPractice',
            new_name='ModelPracticedoesnotmatter',
        ),
    ]
