# Generated by Django 3.2.5 on 2021-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_game_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(default=0),
        ),
    ]
